cart/urls.py
from django.urls import path
from . import views

app_name='cart'


urlpatterns = [
    path('', views.cart, name='cart'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart', include('cart.urls', namespace='cart')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

store/urls.py
from django.urls import path
from . import views
from django.conf import settings

from django.conf.urls.static import static
from .forms import LoginForm
from django.contrib.auth import views as auth_views

app_name='store'


urlpatterns = [
    path('', views.products, name='products'),
    path('checkout/', views.checkout, name='checkout'),
    path('product/<int:pk>/', views.product_detail, name='product-detail'),
    path('delete/<int:id>/', views.delete_order_item, name='delete_order_item'),

    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='store/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_user, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField

class Category(models.Model):
    name=models.CharField(max_length=90, db_index=True)
    slug=models.SlugField(max_length=250, unique=True)

    class Meta:
        verbose_name_plural="categories"

    def __str(self):
        return self.name

# class Customer(models.Model):
#     user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
#     name = models.CharField(max_length=200, null=True)
#     email = models.CharField(max_length=200)
    
#     def __str__(self):
#         return self.name
    
class Product(models.Model):
    name=models.CharField(max_length=200)
    description=RichTextUploadingField(blank=True, null=True)
    price=models.FloatField()
    digital=models.BooleanField(default=False, null=True, blank=True)
    image=models.ImageField(upload_to='uploads/', default='default.jpg')

    def __str__(self):
        return self.name
    
class Order(models.Model):
    customer=models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered=models.DateTimeField(auto_now_add=True)
    complete=models.BooleanField(default=False)
    transaction_id=models.CharField(max_length=90, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems=self.order_items.all()
        sum=0
        for item in orderitems:
            item_new=item.get_total
            sum=sum+item_new
        return sum
        
class OrderItem(models.Model):
    product=models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order=models.ForeignKey(Order, related_name="order_items", on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=1, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_total(self):
        total = self.product.price * self.quantity

        # if self.product.name > str(1):
        #     breakpoint()
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

cart/forms.py
from django import forms
from store.models import Order, OrderItem

class OrderForm(forms.ModelForm):
    class Meta:
        model=OrderItem
        fields=['quantity']

store/forms.py
from django import forms
from store.models import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        # user_name = None
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'form-control'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your Email',
        'class': 'form-control'
    }))
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Your Password',
        'class': 'form-control'
    }))
    password2 = forms.CharField(
        label='Password Confirmation',
        widget=forms.PasswordInput(attrs={
        
        'placeholder': 'Your Password Confirmation',
        'class': 'form-control'
    }))

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('user', 'name', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'form-control'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'form-control'
    }))

cart/views.py
from django.shortcuts import render
from store.models import *
from django.db.models import Count
from django.contrib.auth.decorators import login_required



@login_required(login_url='login/')
def cart(request):
    customer = request.user
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    items = order.order_items.all().order_by('-date_added')
    # items = items.last()
    # items = order.orderitem_set.all()
    # breakpoint()
    # for it in items:
    #     print(it.product.name)
    # dups = order.order_items.values(product.name).annotate(Count('id')).order_by('-date_added').filter(id__count__gt=1)

    context = {'items':items, 'order':order}
    return render(request, 'cart/cart.html', context)

store/views.py
from django.shortcuts import render, redirect
from .models import *
from cart.forms import OrderForm
from store.forms import SignupForm, LoginForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

@login_required(login_url='login/')
def products(request):
    products = Product.objects.all()
    context={'products': products}
    return render(request, 'store/products.html', context)

def product_detail(request, pk):
    product = Product.objects.get(id=pk)
    customer = request.user
    order = Order.objects.get(customer=customer)

    # items = order.order_items.all()
    # context={'product': product, 'order': order, 'items': items}
    if request.method=="POST":
        form=OrderForm(request.POST)
        if form.is_valid():
            orderitem=form.save()
            # product = Product.objects.get(id=pk)
            orderitem.product=product
            product_name=orderitem.product.name

            # customer = request.user.customer
            # order=Order.objects.get(customer=customer)

            orderitem.order=order
            order1=order

            orderitem.save()
            return redirect('cart:cart')
    else:
        form=OrderForm()
    name=OrderItem.objects.filter(product=product)
    context={'product': product, 'form': form, 'name': name, 'customer': customer, 'order': order}

    return render(request, 'store/product_detail.html', context)

def delete_order_item(request, id):
    product = Product.objects.get(id=id)
    customer = request.user
    orderitem=OrderItem.objects.filter(product=product)
    orderitem.delete()
    return redirect('cart:cart')

def order(request):
    return render(request, 'store/order.html')

def checkout(request):
    return render(request, 'store/checkout.html')

def register(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'store/register.html', {
        'form': form
    })

def logout_user(request):
    logout(request)
    return redirect('/')

cart/templates/cart/cart.html
{% extends 'store/base.html' %} {% block content %}


<div class="container mt-3">
    <h2 class="text-center">Your Trolley</h2>
    
    <div class="row">
        <div class="col-md-10">
            
            {% for item in items %}
            <div class="card">
                <div class="row">
                    <div class="col-md-3 card-body"><img src="{{item.product.image.url}}" alt="" style="width:40%"></div>
                    <div class="col-md-3 card-body">{{item.product.name}}</div>
                    <div class="col-md-3 card-body">{{item.quantity}}&nbsp;&nbsp;<a href="{% url 'store:delete_order_item' item.product.id%}" class="btn btn-danger btn-sm">Delete Product</a></div>
                    <div class="col-md-3 card-body">£{{item.get_total}}&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'store:product-detail' item.product.id%}" class="btn btn-warning btn-sm">View Product</a>
                    </div>
                </div>
                Description
                {{item.product.description|safe}}
            </div>
            {% endfor %}
            <div class="card">
                <div class="row">
                    <div class="col-md-3 card-body"></div>
                    <div class="col-md-3 card-body"></div>
                    <div class="col-md-3 card-body">Subtotal:</div>
                    <div class="col-md-3 card-body"><b>£{{order.get_cart_total}}</b></div>
                </div>
            </div>
            <div class="text-end">
                
            </div>
        </div>
    </div>
</div>
{% endblock content%}

store/templates/store/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-sm bg-secondary navbar-dark">
        <div class="container-fluid">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'store:products' %}">All Products</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link text-warning" href="{% url 'store:logout' %}">Logout</a>
          </li>
          {% endif %}
          </ul>
          <!-- <form class="d-flex">
            <input class="form-control me-2" type="text" placeholder="Search" />
            <button class="btn btn-primary" type="button">Search</button>
          </form> -->
          {% if user.is_authenticated %}
            <div class="text-warning">
              Welcome {{request.user.username}}
            </div>
            
          {% endif %}
          <a href="{% url 'cart:cart' %}" class="d-flex btn btn-warning">Trolley</a>
        </div>
      </nav>
    </div>
    <div class="container-fluid">{% block content %} {% endblock %}</div>
  </body>
</html>

store/templates/store/cart.html
{% extends 'store/base.html' %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'css/index.css' %}" />

<h1>Cart page</h1>
{% endblock content %}

store/templates/store/checkout.html
{% extends 'store/base.html' %} {% block content %}
<h1>Checkout page</h1>
{% endblock content %}

store/templates/store/login.html
{% extends 'store/base.html' %}


{% block content %}
<div>
    <h1 class="text-center">Log In</h1>
    <div class="mx-auto col-10 col-md-8 col-lg-6">
        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password }}
            </div>


            <button class="btn btn-warning">Submit</button>
            Not registered? <a href="{% url 'store:register' %}">Register Now</a>
        </form>
    </div>
</div>
{% endblock %}

store/templates/store/product_detail.html
{% extends "store/base.html" %} {% load static %} {% block title %} {{
    product.name }} {% endblock %} {% block content %}
    <div class="container">
      <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first ">
                <img
                class="img-fluid mx-auto d-block"
                width="200px"
                alt="Responsive image"
                src="{{product.image.url}}"
                />
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <div class="row">
                    <div class="col-md-6">
                        <h1 class="mb-0 h4">{{ product.name }} </h1>
                    </div>
                    <div class="col-md-6">
                        £{{product.price}}
                    </div>
                </div>
                <hr>

                <form method="POST" action="">
                    {% csrf_token %}
                    {{form}}
                        <button href="{% url 'cart:cart' %}" class="btn btn-warning" type="submit">Add To Cart</button>
                </form>
                {{product.description|safe}}
                    
            </div>
        </div>
      </main>
    </div>
    
    {% endblock %}
    

store/templates/store/products.html
{% extends 'store/base.html' %} {% block content %}
<h1 class="text-center">All Products</h1>
<div class="row">
  {% for product in products %}
  <div class="col-sm-3">
    <div class="card">
      <img class="card-img-top" src={{ product.image.url }} alt="Card image" style="width:100%">
      <div class="card-body">
        <h4 class="card-title">{{product.name}}</h4>
        <p class="card-text">£{{product.price}}</p>
        <a href="{% url 'store:product-detail' product.id %}" class="btn btn-warning">View Product</a>
      </div>
    </div>
    <br>
  </div>
  {% endfor %}
</div>
{% endblock content%}

store/templates/store/register.html
{% extends 'store/base.html' %}


{% block content %}
<div>
    <h1 class="mb-6 text-3xl text-center">Register</h1>
    <div class="mx-auto col-10 col-md-8 col-lg-6">
    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        

        <button class="btn btn-warning">Submit</button>
        Already registered? <a href="{% url 'store:login' %}">Login Now</a>
    </form>
</div>
</div>
{% endblock %}